### ISSUE TITLE
Issue with a setup for an ES44AC

### ISSUE THREAD

**Issue by btg611** [MagnumMacKivler/RLCPT2#1]
Not sure why exactly I'm having this issue, but whenever I use the 7fdl Standard engine and a config I created for an ES44AC, the locomotive starts but no power can be applied to the traction motors. I've messed around a bit with most of the settings that are relative to power generation and what not, but it hasn't changed anything. Not sure if anyone else has had this issue. Even tried switching from the AC version to the DC one, no luck. Here's my files:
[RLC_Platinum_Gamma_ES44AC.txt](https://github.com/MagnumMacKivler/RLCPT2/files/2827080/RLC_Platinum_Gamma_ES44AC.txt)
[GE_V16_FDL_Late_Standard.txt](https://github.com/MagnumMacKivler/RLCPT2/files/2827085/GE_V16_FDL_Late_Standard.txt)
[GE_ES44DC.txt](https://github.com/MagnumMacKivler/RLCPT2/files/2827104/GE_ES44DC.txt)
I should note that I have made several other configs already that work fine, so I can assure you I understand how to start, operate and create configs for engines with PT2, this one just seems to be giving me some trouble for some reason.

**Comment by MagnumMacKivler** [comment]
What control stand are you using?

**Comment by btg611** [comment]
I've been using the EMD Modern stand with the standard key set. I should note that I've now been having this issue with a few other engines as well, maybe its just something I'm doing wrong, I just have no idea what.

**Comment by MagnumMacKivler** [comment]
Does the engine throttle up at all (sound wise) or does it just stay in idle? I took a look at your configs and I don't see anything wrong with them. My guess is you're either using a stand with a selector lever that you're not setting, or your Isolation switch is off or something like that.

**Comment by btg611** [comment]
Then engine throttles up and everything, it's the strangest thing. It just won't move no matter what I've tried. Just won't put any current to the traction motors. It must be something I did in this config and continue to do, because the default sd40 config works just fine, and I made a config for a FM O6 engine that works fine as well, then I made this one and one for an F& and an SD70 and they all do this.

**Comment by MagnumMacKivler** [comment]
Are you aware of the fact that the PT2 chip you provided references an ES44AC, but the config is set up for an ES44DC? The file name in the PT2 chip doesn't even match the config file name, which means PT2 isn't even looking at this config.

Also that the generator/transition/traction motor info is hilariously wrong (that's not the problem)?

**Comment by btg611** [comment]
This was all set up as a draft, not a final product. I found the issue which as you (very rudely) stated was not the config. Turns out I renamed the main chip. I guess youe coding didn't like that very much. Sorry to have bothered you with this as I clearly have.
