### ISSUE TITLE
[BUG][2.0.64] B-Units Require "CtlTable" Input to Run

### ISSUE THREAD

**Issue by ReverendV92** [MagnumMacKivler/RLCPT2#2]
Current PT throws an error if the B-Unit doesn't have a "CtlTable" value. Grove said it shouldn't need one, and that it was a bug that needed to be fixed/looked at.

The chip errors out if the value isn't present, and won't start.

**Comment by MagnumMacKivler** [comment]
The manual says to spawn a control reader (or stand) regardless of whether you're making a B unit or an A unit. You just don't have to wire MU Master if it's a cabless booster. This isn't a bug.
