### ISSUE TITLE
Script reconizing . as a unknown character 

### ISSUE THREAD

**Issue by yyyyyyyehdydyd** [MagnumMacKivler/RLCPT2#21]
I don't know what happend but now the scripts is saying "Unknown character found (.) at line 76 char 58" im using the RLC Platinum Gamma script.

**Comment by yyyyyyyehdydyd** [comment]
Tried replacing it Same problem still

**Comment by btg611** [comment]
If you go to line 76 in the e2 that's giving you issues and copy the whole line and paste it here it would be more helpful.

**Comment by yyyyyyyehdydyd** [comment]
Lever_Throttle = "gsgtrainsounds/misc/switch_rotating.wav"

**Comment by btg611** [comment]
Did you by chance move PT2 to a new directory? If so, make sure it's set up with the proper file structure.

**Comment by yyyyyyyehdydyd** [comment]
I don't think i moved the PT2 too a new directory since it just stopped recognizing . while i was setting up the script for a locomotive.

**Comment by yyyyyyyehdydyd** [comment]
I just fixed it I don't know how but but after changing the locomotive it just recognized . again didn't work last time time i changed the locomotive
