### ISSUE TITLE
New AAR Stand E2 error

### ISSUE THREAD

**Issue by btg611** [MagnumMacKivler/RLCPT2#26]
When the E2 for the new AAR stand is wired, it returns an error:
`sv: Expression 2 (RLC PT2 Control Stand (2.0.66)
AAR Standard
26-L with SL Independents): entities/gmod_wire_expression2/core/custom/bonecore2.lua:130: attempt to index local 'man' (a nil value)
`
I have no idea what the hell is going on here. Any help would be appreciated.

**Comment by Crash-Skunk** [comment]
The e2 doesn't know how to comprehend operation before being wire linked to the stand itself; therefore, wire link the stand e2 to the stand and refresh, it should fix the issue
