### ISSUE TITLE
Can not get the RLC Platinum Gamma To work

### ISSUE THREAD

**Issue by KarimtheCNUnit2272** [MagnumMacKivler/RLCPT2#27]
I'm trying to build a EMD GP28 High hood But when I Putted in the name for the thing it returns to me with an error saying: Problem including file "ptgamma/locos/EMD/GP28" And I Don't know what the hell is wrong with it If anyone Knows how to Fix I would Appreciate it

**Comment by btg611** [comment]
Do you have a folder named "EMD" in your ptgamma/locos directory? If not, that's your problem. If you try to save a config to a folder that doesn't exist, it will not save. You need to create that folder first, then you can save to it.

**Comment by KarimtheCNUnit2272** [comment]
> Do you have a folder named "EMD" in your ptgamma/locos directory? If not, that's your problem. If you try to save a config to a folder that doesn't exist, it will not save. You need to create that folder first, then you can save to it.

Thank you, it helped out alot

**Comment by btg611** [comment]
Glad I could help! Enjoy.
