### ISSUE TITLE
Rattlecan 2 not working

### ISSUE THREAD

**Issue by jimmykingss** [MagnumMacKivler/RLCPT2#29]
No such method: `xgt:removeArray(n)`

![image_2024-01-04_211824687](https://github.com/MagnumMacKivler/RLCPT2/assets/47538595/8826c92b-c451-4f4b-963e-39739db45da5)

**Comment by btg611** [comment]
This appears to be due to a Wiremod update, as is the case with many of the issues plaguing the Trainbuild community as of late.

**Comment by jimmykingss** [comment]
> This appears to be due to a Wiremod update, as is the case with many of the issues plaguing the Trainbuild community as of late.

is there a possible fix? or does it have to be an older version of wire mod?

**Comment by btg611** [comment]
To my knowledge, the server has to be using a backdated version of Wiremod for this to be fixed, and that's about the only solution without re-doing much of the code within PT1 and Rattlecan.

I'm currently performing some tests on my server to see if an old branch of Wiremod is still suitable for trainbuild purposes, I'll report my findings here as soon as I finish, since it seems the devs have abandoned the issues tab here.

**Comment by btg611** [comment]
Ok, so I can confirm that the old branch of Wiremod that is "origin/add-egp-3d-view" from 3 years ago DOES work well, allows for use of PT1 and Rattlecan, and only the serverside needs to be using the backdated version. 

The only issue I'm encountering is a Wiremod related lua error related to holograms that doesn't seem to have any unintended side effects other than spamming console and being annoying.

**Comment by jimmykingss** [comment]
while I'm here is this project dead? or does it take time to update also is there any alternative for Rattlecan 2 with the latest version of wire mod?

**Comment by Monkatraz** [comment]
Did Wire break my 4 year old code? So much has happened in my life since then. Not sure I could even edit it now and make sense of it lol. I'd probably reformat it to have spaces between `if` and the condition, what I was thinking lmao.

If I ever make a come back to train build I'll make sure to rewrite Rattlecan in Lua or TypeScript lol.

**Comment by Monkatraz** [comment]
Out of curiosity did they break my code for any good reason? Why'd they make the breaking changes?

**Comment by jimmykingss** [comment]
It's a bit late but how do I know probably a breaking change or something and I'm also happy to see you alive and possibly remaking the rattle can E2 with Starfall or E2 again

**Comment by btg611** [comment]
> while I'm here is this project dead? or does it take time to update also is there any alternative for Rattlecan 2 with the latest version of wire mod?

This project is not dead, but it will eventually be replaced by RLC Delta, which is in the works and has been for some time.

The alternative for Rattlecan is standard holoclip. That's the only other choice, I'm afraid.

> It's a bit late but how do I know probably a breaking change or something and I'm also happy to see you alive and possibly remaking the rattle can E2 with Starfall or E2 again

When a script that worked just fine the day before breaks the next day on the same server after Wiremod updated, that's how you know Wiremod broke it.

**Comment by btg611** [comment]
> Did Wire break my 4 year old code? So much has happened in my life since then. Not sure I could even edit it now and make sense of it lol. I'd probably reformat it to have spaces between `if` and the condition, what I was thinking lmao.
> 
> If I ever make a come back to train build I'll make sure to rewrite Rattlecan in Lua or TypeScript lol.

Dude, if you ever do decide to rewrite it in LUA or TS it would be such a Godsend. 

Hope you've been well!

**Comment by jimmykingss** [comment]
> > while I'm here is this project dead? or does it take time to update also is there any alternative for Rattlecan 2 with the latest version of wire mod?
> 
> This project is not dead, but it will eventually be replaced by RLC Delta, which is in the works and has been for some time.
> 
> The alternative for Rattlecan is standard holoclip. That's the only other choice, I'm afraid.
> 
> > It's a bit late but how do I know probably a breaking change or something and I'm also happy to see you alive and possibly remaking the rattle can E2 with Starfall or E2 again
> 
> When a script that worked just fine the day before breaks the next day on the same server after Wiremod updated, that's how you know Wiremod broke it.

thanks for the information. I can't wait for the RLC Delta!
