### ISSUE TITLE
[BUG][2.0.64] Using ".controls" Prints Multiple Times

### ISSUE THREAD

**Issue by ReverendV92** [MagnumMacKivler/RLCPT2#3]
While a locomotive is placed somewhere that you own, when sitting in someone else's locomotive and running the ".controls" chat command, it will print both your config and theirs back-to-back.

**Comment by MagnumMacKivler** [comment]
Not really a bug. All chat commands operate on all relevant units unless a number is specified. So if you had loco 1234 out and someone else had loco 5678 out, you'd type `.controls:1234` to view your unit's control setup and `.controls:5678` to view the other person's (if you were in their seat, that is).
