### ISSUE TITLE
Gauge 

### ISSUE THREAD

**Issue by padd23** [MagnumMacKivler/RLCPT2#33]
![image](https://github.com/MagnumMacKivler/RLCPT2/assets/172188433/aebb475c-44fb-4756-942b-18d65431fe67)

The gauge is covered with a white area. Bell has the same problem. Is it the wiremode error itself? help.
 (There is no problem with addon)

**Comment by btg611** [comment]
Make sure all wiremod expression2 extensions are enabled if you're in single player. Go into console (hit ~), type:
 wire_expression2_extension_enable
Then hit enter. It will return a list of extensions that need to be enabled.
Additionally, make sure holomodelany is set to 1.

**Comment by padd23** [comment]
It was helpful. Thank you!
