### ISSUE TITLE
[Bug/User Error?] Dual_Control_Stand_Mux not passing through config version

### ISSUE THREAD

**Issue by SeanTheMahn** [MagnumMacKivler/RLCPT2#4]
When I try to set up dual control stands using the code stated in the title, PT Gamma doesnt recognize the versions of the control stand and the control config, spitting back this error

[RLCPT] Note: One of your configs are out of date! Please use configs compatible with Gamma 2.0.64!
--------
Engine Config version: 2.0.63
Locomotive Config version: 2.0.63
Control Stand/Reader version: unknown
Control Config version: unknown

I have wired everything together that seems self explanatory (CtlTable_F to the front control stand, CtlTable output to the PT chip, etc.)

Am I missing something obvious or is it a problem with Dual_Control_Stand_Mux not passing through the version of the stands to the PT chip?

**Comment by btg611** [comment]
There's now a hotfix in the code tab
